#!/bin/bash

# Function to display help message
display_help() {
    echo "Usage: $0 [OPTIONS] <file_path>"
    echo "OPTIONS:"
    echo "  -h, --help       Display this help message"
    echo "About:"
    echo "  This script helps to document files in the system. It takes as input a path to a file"
    echo "  and creates a JSON file in the same folder with the file documentation."
    echo "  For more information, please visit: https://github.com/Toozig/fileMaster"
    echo "  Written by: Toozig"
    exit 0
}

# Function to check for updates in git repository
check_git_updates() {
    git fetch origin
    LOCAL=$(git rev-parse HEAD)
    REMOTE=$(git rev-parse @{u})
    if [ $LOCAL != $REMOTE ]; then
        echo "Git repository has updates. Pulling changes..."
        git pull origin master
        return 0
    else
        echo "Git repository is up to date."
        return 1
    fi
}

# Parse command-line options
while getopts ":h-:" opt; do
    case $opt in
        -)
            case "${OPTARG}" in
                help)
                    display_help
                    ;;
                *)
                    echo "Invalid option: --${OPTARG}" >&2
                    exit 1
                    ;;
            esac
            ;;
        h)
            display_help
            ;;
        *)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

# Check if the user requested help
if [ "$#" -eq 0 ]; then
    display_help
fi

# Check if a file path is provided as an argument
file_path="$1"
if [ ! -f "$file_path" ]; then
    echo "Error: File not found at $file_path"
    exit 1
fi

# Get the absolute path of the directory containing the file
dir_path=$(dirname "$(realpath "$file_path")")

# Define the Docker image name
docker_image="file_master"

# This command will build the Docker image if it doesn’t exist or if there are updates in the git repository
(docker image inspect "$docker_image" &> /dev/null || check_git_updates) && docker build -t "$docker_image" fileMaster_bin/


# Run the Docker container with the file's directory as a volume
# Set the working directory inside the container and pass the relative file path
docker run -v "$dir_path:/files" -p 4000:80 -it "$docker_image" python main.py "/files/$(basename "$file_path")"
